from __future__ import annotations

from .checks import CHECKS, CheckFunc, CheckResult, LintContext, run, run_checks
from .checks.base_diff_scope import check_base_diff_scope
from .checks.basic import (
    check_file_identity,
    check_ordered_heading_contracts,
    check_required_file_contracts,
    check_text_contracts,
    extract_contract_value,
    heading_lines,
)
from .checks.epilogue import canonical_epilogue_heading, check_epilogue_order
from .checks.hooks_json import check_hooks_json
from .checks.marker_manifest import (
    allow_empty_field_keys,
    check_marker_manifests,
    marker_present,
    parse_sources_manifest,
)
from .checks.mechanical import check_mechanical
from .checks.ui_relevance import (
    check_ui_relevance_contracts,
    has_basename_prefix,
    has_segment,
    has_suffix,
    is_ui_relevant_path,
    normalize_fixture_expected,
    normalize_path,
    parse_fixture_matrix,
    path_segments,
)
from .cli import add_arguments, load_registry, main, parse_cli
from .frontmatter import (
    expected_arguments,
    expected_invocation,
    parse_frontmatter,
    parse_frontmatter_bool,
)
from .io import read_text, rel, resolve, sha256, skill_paths
from .markdown import (
    escape_markdown_table_cell,
    normalize_markdown_cell,
    split_markdown_table_row,
)
from .readme import (
    AgentReference,
    HookReference,
    SkillReference,
    agent_name_from_readme_cell,
    check_readme_agent_sync,
    check_readme_extra_skill_rows,
    check_readme_hook_sync,
    check_readme_skill_rows_sync,
    check_readme_skill_sync,
    generated_readme_block_bounds,
    hook_event_label,
    hook_name_from_command,
    hook_name_from_readme_cell,
    load_agent_references,
    load_hook_references,
    load_skill_references,
    name_from_readme_cell,
    readme_component_rows,
    readme_relative_for_component_sync,
    readme_skill_rows,
    render_agent_reference_row,
    render_hook_reference_row,
    render_readme_agent_sync,
    render_readme_component_sync,
    render_readme_hook_sync,
    render_readme_skill_rows_sync,
    render_readme_skill_sync,
    render_skill_reference_row,
    replace_generated_readme_block,
    skill_name_from_readme_cell,
    skill_reference_from_frontmatter,
)
from .schema import (
    DEFAULT_CONTRACT_SCHEMA,
    DEFAULT_CONTRACT_SCHEMA_PATH,
    contract_schema_path,
    load_contract_schema,
    load_contract_schema_file,
    load_default_contract_schema,
    schema_skill_frontmatter_fields,
    schema_source_manifest,
    skill_frontmatter_field_by_loader_property,
    skill_frontmatter_fields_by_type,
    skill_frontmatter_required_fields,
    source_manifest_one_of_fields,
    source_manifest_required_fields,
)
from .strings import is_empty_value, normalize_value, shorten, strip_quotes

__all__ = [
    "CHECKS",
    "DEFAULT_CONTRACT_SCHEMA",
    "DEFAULT_CONTRACT_SCHEMA_PATH",
    "AgentReference",
    "CheckFunc",
    "CheckResult",
    "HookReference",
    "LintContext",
    "SkillReference",
    "add_arguments",
    "agent_name_from_readme_cell",
    "allow_empty_field_keys",
    "canonical_epilogue_heading",
    "check_base_diff_scope",
    "check_epilogue_order",
    "check_file_identity",
    "check_hooks_json",
    "check_marker_manifests",
    "check_mechanical",
    "check_ordered_heading_contracts",
    "check_readme_agent_sync",
    "check_readme_extra_skill_rows",
    "check_readme_hook_sync",
    "check_readme_skill_sync",
    "check_readme_skill_rows_sync",
    "check_required_file_contracts",
    "check_text_contracts",
    "check_ui_relevance_contracts",
    "contract_schema_path",
    "escape_markdown_table_cell",
    "expected_arguments",
    "expected_invocation",
    "extract_contract_value",
    "generated_readme_block_bounds",
    "heading_lines",
    "hook_event_label",
    "hook_name_from_command",
    "hook_name_from_readme_cell",
    "has_basename_prefix",
    "has_segment",
    "has_suffix",
    "is_empty_value",
    "is_ui_relevant_path",
    "load_contract_schema",
    "load_contract_schema_file",
    "load_default_contract_schema",
    "load_registry",
    "load_agent_references",
    "load_hook_references",
    "load_skill_references",
    "main",
    "marker_present",
    "name_from_readme_cell",
    "normalize_fixture_expected",
    "normalize_markdown_cell",
    "normalize_path",
    "normalize_value",
    "parse_cli",
    "parse_fixture_matrix",
    "parse_frontmatter",
    "parse_frontmatter_bool",
    "parse_sources_manifest",
    "path_segments",
    "read_text",
    "readme_component_rows",
    "readme_relative_for_component_sync",
    "readme_skill_rows",
    "rel",
    "render_agent_reference_row",
    "render_hook_reference_row",
    "render_readme_agent_sync",
    "render_readme_component_sync",
    "render_readme_hook_sync",
    "render_readme_skill_sync",
    "render_readme_skill_rows_sync",
    "render_skill_reference_row",
    "replace_generated_readme_block",
    "resolve",
    "run",
    "run_checks",
    "schema_skill_frontmatter_fields",
    "schema_source_manifest",
    "sha256",
    "shorten",
    "skill_frontmatter_field_by_loader_property",
    "skill_frontmatter_fields_by_type",
    "skill_frontmatter_required_fields",
    "skill_name_from_readme_cell",
    "skill_paths",
    "skill_reference_from_frontmatter",
    "source_manifest_one_of_fields",
    "source_manifest_required_fields",
    "split_markdown_table_row",
    "strip_quotes",
]
