"use strict";

const path = require("path");
const { normalizeName } = require("./frontmatter");
const {
  pathExists,
  readText,
  resolveManagedChild,
  writeText,
} = require("./filesystem");

async function stageCodexConfig(
  codexRoot,
  codexStagingRoot,
  bundle,
  previousEntries,
  pluginName,
) {
  const configPath = path.join(codexRoot, "config.toml");
  const existing = (await pathExists(configPath)) ? await readText(configPath) : "";
  const config = renderCodexConfigTables(bundle.mcpServers);
  let updated = existing;

  if (config.tables.length > 0) {
    updated = upsertTomlTables(
      updated || "# Generated by kramme-cc-workflow\n",
      config.tables,
      { removeHeaders: config.removeHeaders },
    );
  }

  if (bundle.codexPlugin) {
    updated = upsertTomlTables(
      updated,
      renderCodexHookPluginConfigTables(codexRoot, bundle.codexPlugin),
    );
  } else if (
    previousEntries.pluginCaches.length > 0 ||
    previousEntries.hookMarketplaces.length > 0
  ) {
    const hookConfigRef = codexHookPluginConfigRef(pluginName);
    updated = removeTomlTables(updated, [
      codexMarketplaceTableHeader(hookConfigRef),
      codexPluginTableHeader(hookConfigRef),
    ]);
  }

  if (updated === undefined || updated === null || updated === existing) {
    return null;
  }

  const stagedConfigPath = path.join(codexStagingRoot, "config.toml");
  await writeText(stagedConfigPath, updated);
  return stagedConfigPath;
}

function codexHookPluginConfigRef(pluginName) {
  const name = normalizeName(pluginName);
  return { name, marketplaceName: name };
}

function codexHookMarketplaceEntry(codexPlugin) {
  return path.join(".kramme-plugin-marketplaces", codexPlugin.marketplaceName);
}

function codexHookMarketplaceRoot(codexRoot, codexPlugin) {
  return resolveManagedChild(
    codexRoot,
    codexHookMarketplaceEntry(codexPlugin),
    "Codex hook marketplace entry",
  );
}

function codexHookPluginCacheEntry(codexPlugin) {
  return path.join(
    "cache",
    codexPlugin.marketplaceName,
    codexPlugin.name,
    codexPlugin.version,
  );
}

function renderCodexHookPluginConfigTables(codexRoot, codexPlugin) {
  const source = codexHookMarketplaceRoot(codexRoot, codexPlugin);
  const lastUpdated = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
  return [
    {
      header: codexMarketplaceTableHeader(codexPlugin),
      content: [
        codexMarketplaceTableHeader(codexPlugin),
        `last_updated = ${formatTomlString(lastUpdated)}`,
        'source_type = "local"',
        `source = ${formatTomlString(source)}`,
      ].join("\n"),
    },
    {
      header: codexPluginTableHeader(codexPlugin),
      content: [codexPluginTableHeader(codexPlugin), "enabled = true"].join(
        "\n",
      ),
    },
  ];
}

function codexMarketplaceTableHeader(codexPlugin) {
  return `[marketplaces.${formatTomlKey(codexPlugin.marketplaceName)}]`;
}

function codexPluginTableHeader(codexPlugin) {
  return `[plugins.${formatTomlKey(`${codexPlugin.name}@${codexPlugin.marketplaceName}`)}]`;
}

function upsertTomlTables(existing, tables, { removeHeaders } = {}) {
  const headers = removeHeaders ?? tables.map((table) => table.header);
  const withoutExisting = removeTomlTables(existing, headers).trimEnd();
  const renderedTables = tables.map((table) => table.content.trimEnd());
  return (
    [withoutExisting, ...renderedTables].filter(Boolean).join("\n\n") + "\n"
  );
}

function removeTomlTables(existing, headers) {
  let result = existing;
  for (const header of headers) {
    result = removeTomlTable(result, header);
  }
  return (
    result.replace(/\n{3,}/g, "\n\n").trimEnd() + (result.trim() ? "\n" : "")
  );
}

function removeTomlTable(existing, header) {
  const lines = String(existing ?? "").split(/\r?\n/);
  const kept = [];
  let skipping = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed === header) {
      skipping = true;
      continue;
    }
    if (skipping && /^\[/.test(trimmed)) {
      skipping = false;
    }
    if (!skipping) {
      kept.push(line);
    }
  }
  return kept.join("\n");
}

function renderCodexConfigTables(mcpServers) {
  if (!mcpServers || Object.keys(mcpServers).length === 0) {
    return { tables: [], removeHeaders: [] };
  }

  const tables = [];
  const removeHeaders = [];
  for (const [name, server] of Object.entries(mcpServers)) {
    const key = formatTomlKey(name);
    const keyVariants = Array.from(new Set([key, formatTomlString(name)]));
    const header = `[mcp_servers.${key}]`;
    const envHeader = `[mcp_servers.${key}.env]`;
    const lines = [header];
    let envTable = null;
    for (const variant of keyVariants) {
      removeHeaders.push(`[mcp_servers.${variant}]`);
      removeHeaders.push(`[mcp_servers.${variant}.env]`);
    }

    if (server.command) {
      lines.push(`command = ${formatTomlString(server.command)}`);
      if (server.args && server.args.length > 0) {
        const args = server.args.map((arg) => formatTomlString(arg)).join(", ");
        lines.push(`args = [${args}]`);
      }

      if (server.env && Object.keys(server.env).length > 0) {
        const envLines = [envHeader];
        for (const [envKey, value] of Object.entries(server.env)) {
          envLines.push(
            `${formatTomlKey(envKey)} = ${formatTomlString(value)}`,
          );
        }
        envTable = { header: envHeader, content: envLines.join("\n") };
      }
    } else if (server.url) {
      lines.push(`url = ${formatTomlString(server.url)}`);
      if (server.headers && Object.keys(server.headers).length > 0) {
        lines.push(`http_headers = ${formatTomlInlineTable(server.headers)}`);
      }
    }

    tables.push({ header, content: lines.join("\n") });
    if (envTable) {
      tables.push(envTable);
    }
  }

  return { tables, removeHeaders };
}

function formatTomlString(value) {
  return JSON.stringify(value);
}

function formatTomlKey(value) {
  if (/^[A-Za-z0-9_-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

function formatTomlInlineTable(entries) {
  const parts = Object.entries(entries).map(
    ([key, value]) => `${formatTomlKey(key)} = ${formatTomlString(value)}`,
  );
  return `{ ${parts.join(", ")} }`;
}

module.exports = {
  codexHookMarketplaceEntry,
  codexHookMarketplaceRoot,
  codexHookPluginCacheEntry,
  stageCodexConfig,
};
