"use strict";

const path = require("path");
const { parse: parseToml } = require("smol-toml");
const { normalizeName } = require("./frontmatter");
const {
  pathExists,
  readText,
  resolveManagedChild,
  writeText,
} = require("./filesystem");

/**
 * @typedef {Object} TomlTable
 * @property {string} header
 * @property {string} content
 *
 * @typedef {import("./contracts").CodexBundle} CodexBundle
 * @typedef {import("./contracts").CodexHookPlugin} CodexHookPlugin
 * @typedef {import("./contracts").CodexMcpServer} CodexMcpServer
 * @typedef {import("./contracts").InstallEntries} InstallEntries
 * @typedef {Pick<InstallEntries, "pluginCaches" | "hookMarketplaces">} PreviousConfigEntries
 * @typedef {{ name: string, marketplaceName: string }} CodexHookPluginRef
 * @typedef {Pick<CodexBundle, "mcpServers" | "codexPlugin">} CodexConfigBundle
 */

/**
 * @param {string} codexRoot
 * @param {string} codexStagingRoot
 * @param {CodexConfigBundle} bundle
 * @param {PreviousConfigEntries} previousEntries
 * @param {string} pluginName
 */
async function stageCodexConfig(
  codexRoot,
  codexStagingRoot,
  bundle,
  previousEntries,
  pluginName,
) {
  const configPath = path.join(codexRoot, "config.toml");
  const existing = (await pathExists(configPath))
    ? await readText(configPath)
    : "";
  const config = renderCodexConfigTables(bundle.mcpServers);
  let updated = existing;

  if (config.tables.length > 0) {
    updated = upsertTomlTables(
      updated || "# Generated by kramme-cc-workflow\n",
      config.tables,
      { removeHeaders: config.removeHeaders },
    );
  }

  if (bundle.codexPlugin) {
    updated = upsertTomlTables(
      updated,
      renderCodexHookPluginConfigTables(codexRoot, bundle.codexPlugin),
    );
  } else if (
    previousEntries.pluginCaches.length > 0 ||
    previousEntries.hookMarketplaces.length > 0
  ) {
    const hookConfigRef = codexHookPluginConfigRef(pluginName);
    updated = removeTomlTables(updated, [
      codexMarketplaceTableHeader(hookConfigRef),
      codexPluginTableHeader(hookConfigRef),
    ]);
  }

  if (updated === undefined || updated === null || updated === existing) {
    return null;
  }

  const stagedConfigPath = path.join(codexStagingRoot, "config.toml");
  await writeText(stagedConfigPath, updated);
  return stagedConfigPath;
}

/** @param {string} pluginName @returns {CodexHookPluginRef} */
function codexHookPluginConfigRef(pluginName) {
  const name = normalizeName(pluginName);
  return { name, marketplaceName: name };
}

/** @param {CodexHookPluginRef} codexPlugin */
function codexHookMarketplaceEntry(codexPlugin) {
  return path.join(".kramme-plugin-marketplaces", codexPlugin.marketplaceName);
}

/** @param {string} codexRoot @param {CodexHookPluginRef} codexPlugin */
function codexHookMarketplaceRoot(codexRoot, codexPlugin) {
  return resolveManagedChild(
    codexRoot,
    codexHookMarketplaceEntry(codexPlugin),
    "Codex hook marketplace entry",
  );
}

/** @param {CodexHookPlugin} codexPlugin */
function codexHookPluginCacheEntry(codexPlugin) {
  return path.join(
    "cache",
    codexPlugin.marketplaceName,
    codexPlugin.name,
    codexPlugin.version,
  );
}

/** @param {string} codexRoot @param {CodexHookPlugin} codexPlugin @returns {TomlTable[]} */
function renderCodexHookPluginConfigTables(codexRoot, codexPlugin) {
  const source = codexHookMarketplaceRoot(codexRoot, codexPlugin);
  const lastUpdated = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
  return [
    {
      header: codexMarketplaceTableHeader(codexPlugin),
      content: [
        codexMarketplaceTableHeader(codexPlugin),
        `last_updated = ${formatTomlString(lastUpdated)}`,
        'source_type = "local"',
        `source = ${formatTomlString(source)}`,
      ].join("\n"),
    },
    {
      header: codexPluginTableHeader(codexPlugin),
      content: [codexPluginTableHeader(codexPlugin), "enabled = true"].join(
        "\n",
      ),
    },
  ];
}

/** @param {CodexHookPluginRef} codexPlugin */
function codexMarketplaceTableHeader(codexPlugin) {
  return `[marketplaces.${formatTomlKey(codexPlugin.marketplaceName)}]`;
}

/** @param {CodexHookPluginRef} codexPlugin */
function codexPluginTableHeader(codexPlugin) {
  return `[plugins.${formatTomlKey(`${codexPlugin.name}@${codexPlugin.marketplaceName}`)}]`;
}

/**
 * @param {string} existing
 * @param {TomlTable[]} tables
 * @param {{ removeHeaders?: string[] }} [options]
 */
function upsertTomlTables(existing, tables, { removeHeaders } = {}) {
  const headers = removeHeaders ?? tables.map((table) => table.header);
  const withoutExisting = removeTomlTables(existing, headers).trimEnd();
  const renderedTables = tables.map((table) => table.content.trimEnd());
  const updated =
    [withoutExisting, ...renderedTables].filter(Boolean).join("\n\n") + "\n";
  validateTomlDocument(updated, "updated Codex config");
  return updated;
}

/** @param {string} existing @param {string[]} headers */
function removeTomlTables(existing, headers) {
  const removePaths = tomlHeaderPathKeys(headers);
  const lines = String(existing ?? "").split(/\r?\n/);
  const kept = [];
  let skipping = false;

  for (const line of lines) {
    const header = parseTomlTableHeader(line);
    if (header) {
      skipping = removePaths.has(tomlPathKey(header.path));
      if (skipping) continue;
    }
    if (!skipping) {
      kept.push(line);
    }
  }

  const updated = normalizeTomlWhitespace(kept.join("\n"));
  validateTomlDocument(updated, "updated Codex config");
  return updated;
}

/** @param {string[]} headers */
function tomlHeaderPathKeys(headers) {
  const paths = new Set();
  for (const header of headers) {
    const parsed = parseTomlTableHeader(header);
    if (!parsed) {
      throw new Error(`Invalid managed TOML table header: ${header}`);
    }
    paths.add(tomlPathKey(parsed.path));
  }
  return paths;
}

/** @param {string} line */
function parseTomlTableHeader(line) {
  const trimmed = String(line ?? "").trim();
  const isArrayTable = trimmed.startsWith("[[");
  if (!trimmed.startsWith("[")) return null;

  const closeIndex = findTomlHeaderClose(trimmed, { isArrayTable });
  if (closeIndex === -1) return null;

  const trailing = trimmed.slice(closeIndex + (isArrayTable ? 2 : 1)).trim();
  if (trailing && !trailing.startsWith("#")) return null;

  const path = parseTomlDottedKey(
    trimmed.slice(isArrayTable ? 2 : 1, closeIndex).trim(),
  );
  return path && path.length > 0 ? { path } : null;
}

/**
 * @param {string} value
 * @param {{ isArrayTable?: boolean }} [options]
 */
function findTomlHeaderClose(value, { isArrayTable } = {}) {
  let quote = null;
  let escaping = false;
  for (let index = isArrayTable ? 2 : 1; index < value.length; index += 1) {
    const char = value[index];
    if (quote) {
      if (quote === '"' && char === "\\" && !escaping) {
        escaping = true;
        continue;
      }
      if (char === quote && !escaping) {
        quote = null;
      }
      escaping = false;
      continue;
    }
    if (char === '"' || char === "'") {
      quote = char;
      continue;
    }
    if (char === "]") {
      if (!isArrayTable) return index;
      if (value[index + 1] === "]") return index;
    }
  }
  return -1;
}

/** @param {string} value @returns {string[] | null} */
function parseTomlDottedKey(value) {
  /** @type {string[]} */
  const parts = [];
  let current = "";
  let quote = null;
  let escaping = false;

  for (const char of value) {
    if (quote) {
      current += char;
      if (quote === '"' && char === "\\" && !escaping) {
        escaping = true;
        continue;
      }
      if (char === quote && !escaping) {
        quote = null;
      }
      escaping = false;
      continue;
    }

    if (char === '"' || char === "'") {
      quote = char;
      current += char;
      continue;
    }
    if (char === ".") {
      const part = parseTomlKeyPart(current);
      if (part === null) return null;
      parts.push(part);
      current = "";
      continue;
    }
    current += char;
  }

  if (quote) return null;
  const part = parseTomlKeyPart(current);
  if (part === null) return null;
  parts.push(part);
  return parts;
}

/** @param {string} value @returns {string | null} */
function parseTomlKeyPart(value) {
  const trimmed = String(value ?? "").trim();
  if (!trimmed) return null;
  if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
    try {
      return JSON.parse(trimmed);
    } catch (_error) {
      return null;
    }
  }
  if (trimmed.startsWith("'") && trimmed.endsWith("'")) {
    return trimmed.slice(1, -1);
  }
  if (/^[A-Za-z0-9_-]+$/.test(trimmed)) return trimmed;
  return null;
}

/** @param {string[]} pathParts */
function tomlPathKey(pathParts) {
  return JSON.stringify(pathParts);
}

/** @param {string} value */
function normalizeTomlWhitespace(value) {
  const content = String(value ?? "");
  return (
    content.replace(/\n{3,}/g, "\n\n").trimEnd() + (content.trim() ? "\n" : "")
  );
}

/** @param {string} value @param {string} label */
function validateTomlDocument(value, label) {
  const content = String(value ?? "");
  if (!content.trim()) return;
  try {
    parseToml(content);
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new Error(`Invalid ${label}: ${detail}`);
  }
}

/**
 * @param {Record<string, CodexMcpServer> | null | undefined} mcpServers
 * @returns {{ tables: TomlTable[], removeHeaders: string[] }}
 */
function renderCodexConfigTables(mcpServers) {
  if (!mcpServers || Object.keys(mcpServers).length === 0) {
    return { tables: [], removeHeaders: [] };
  }

  const tables = [];
  const removeHeaders = [];
  for (const [name, server] of Object.entries(mcpServers)) {
    const key = formatTomlKey(name);
    const keyVariants = Array.from(new Set([key, formatTomlString(name)]));
    const header = `[mcp_servers.${key}]`;
    const envHeader = `[mcp_servers.${key}.env]`;
    const lines = [header];
    let envTable = null;
    for (const variant of keyVariants) {
      removeHeaders.push(`[mcp_servers.${variant}]`);
      removeHeaders.push(`[mcp_servers.${variant}.env]`);
    }

    if (server.command) {
      lines.push(`command = ${formatTomlString(server.command)}`);
      if (server.args && server.args.length > 0) {
        const args = server.args.map((arg) => formatTomlString(arg)).join(", ");
        lines.push(`args = [${args}]`);
      }

      if (server.env && Object.keys(server.env).length > 0) {
        const envLines = [envHeader];
        for (const [envKey, value] of Object.entries(server.env)) {
          envLines.push(
            `${formatTomlKey(envKey)} = ${formatTomlString(value)}`,
          );
        }
        envTable = { header: envHeader, content: envLines.join("\n") };
      }
    } else if (server.url) {
      lines.push(`url = ${formatTomlString(server.url)}`);
      if (server.headers && Object.keys(server.headers).length > 0) {
        lines.push(`http_headers = ${formatTomlInlineTable(server.headers)}`);
      }
    }

    tables.push({ header, content: lines.join("\n") });
    if (envTable) {
      tables.push(envTable);
    }
  }

  return { tables, removeHeaders };
}

/** @param {string} value */
function formatTomlString(value) {
  return JSON.stringify(value);
}

/** @param {string} value */
function formatTomlKey(value) {
  if (/^[A-Za-z0-9_-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

/** @param {Record<string, string>} entries */
function formatTomlInlineTable(entries) {
  const parts = Object.entries(entries).map(
    ([key, value]) => `${formatTomlKey(key)} = ${formatTomlString(value)}`,
  );
  return `{ ${parts.join(", ")} }`;
}

module.exports = {
  codexHookMarketplaceEntry,
  codexHookMarketplaceRoot,
  codexHookPluginCacheEntry,
  stageCodexConfig,
};
