#!/bin/bash
# Deterministic grader for commit message generation
# Checks: file exists, first line length, no AI attribution, substantive content

passed=0
total=5
checks="["

check() {
  local name="$1" result="$2" msg="$3"
  if [ "$result" = "true" ]; then
    passed=$((passed + 1))
    checks="${checks}{\"name\":\"${name}\",\"passed\":true,\"message\":\"${msg}\"},"
  else
    checks="${checks}{\"name\":\"${name}\",\"passed\":false,\"message\":\"${msg}\"},"
  fi
}

FILE="commit-msg.txt"

# Check 1: File exists
if [ ! -f "$FILE" ]; then
  echo "{\"score\":0.00,\"details\":\"commit-msg.txt not found\",\"checks\":[{\"name\":\"file-exists\",\"passed\":false,\"message\":\"commit-msg.txt not found\"}]}"
  exit 0
fi
check "file-exists" "true" "commit-msg.txt exists"

content=$(cat "$FILE")
first_line=$(head -n 1 "$FILE")
first_line_len=${#first_line}

# Check 2: First line under 72 characters
if [ "$first_line_len" -le 72 ]; then
  check "subject-length" "true" "Subject line is ${first_line_len} chars (under 72)"
else
  check "subject-length" "false" "Subject line is ${first_line_len} chars (over 72)"
fi

# Check 3: No AI attribution markers
if echo "$content" | grep -qi "Co-Authored-By\|Generated by\|Written with Claude\|Written by AI\|AI-generated"; then
  check "no-ai-attribution" "false" "Found AI attribution marker"
else
  check "no-ai-attribution" "true" "No AI attribution markers"
fi

# Check 4: Subject line has >10 characters (substantive)
if [ "$first_line_len" -gt 10 ]; then
  check "subject-substantive" "true" "Subject line has ${first_line_len} chars (over 10)"
else
  check "subject-substantive" "false" "Subject line is only ${first_line_len} chars (need >10)"
fi

# Check 5: No conventional commit prefix (not for branch commits)
if echo "$first_line" | grep -qE '^(feat|fix|chore|docs|style|refactor|test|ci|build|perf)(\(.*\))?:'; then
  check "no-conventional-prefix" "false" "Found conventional commit prefix (not for branch commits)"
else
  check "no-conventional-prefix" "true" "No conventional commit prefix"
fi

checks="${checks%,}]"
score=$(awk "BEGIN {printf \"%.2f\", $passed/$total}")
echo "{\"score\":${score},\"details\":\"${passed}/${total} checks passed\",\"checks\":${checks}}"
