#!/usr/bin/env bats

@test "SIW issue-to-PR prepares one safe branch before autonomous implementation" {
	run bash -c '
	    set -e
    cd "'"$BATS_TEST_DIRNAME"'/.."
    skill="skills/kramme:siw:issue-to-pr/SKILL.md"

    test -f "$skill"
    grep -qF "argument-hint: \"<issue-id> [--strict] [--ship]\"" "$skill"
    grep -qF "disable-model-invocation: true" "$skill"
    grep -qF "kramme:siw:issue-implement" "$skill"
    grep -qF "{issue-id} --auto" "$skill"
    grep -qF "kramme:pr:complete-work" "$skill"
    grep -qF -- "--archive-key siw-issue-to-pr" "$skill"
    grep -qF "git status --porcelain" "$skill"
    grep -qF "git check-ref-format --branch \"{issue-branch}\"" "$skill"
    grep -qF "gh pr list --head \"{issue-branch}\" --state all" "$skill"
    grep -qF "git ls-remote --heads origin \"refs/heads/{issue-branch}\"" "$skill"
	    grep -qF "git diff --quiet \"{intake-head}\" \"origin/{base-branch}\" -- siw/" "$skill"
	    grep -qF "requires all committed SIW planning state to be landed on the fetched base" "$skill"
	    grep -qF "git merge-base \"origin/{base-branch}\" HEAD" "$skill"
	    grep -qF "matching only the SIW subtree is insufficient" "$skill"
	    grep -qF "set \`EXECUTION_MODE=complete-resume\`" "$skill"
	    grep -qF "do not invoke \`kramme:siw:issue-implement\` again" "$skill"
	    grep -qF "continue directly to Step 4" "$skill"
	    grep -qF "## Resolution" "$skill"
	    grep -qF "status \`DONE\` or \`IN REVIEW\`" "$skill"
    grep -qF "issue file, \`siw/OPEN_ISSUES_OVERVIEW.md\`, and \`siw/LOG.md\`" "$skill"
    grep -qF "Do not invoke \`kramme:workflow-artifacts:cleanup --auto\`" "$skill"
  '

	[ "$status" -eq 0 ] || { echo "$output"; false; }

	run python3 \
		"$BATS_TEST_DIRNAME/test_helper/guidance_contracts.py" \
		issue-intake-state \
		"$BATS_TEST_DIRNAME/../skills/kramme:siw:issue-to-pr/SKILL.md"
	[ "$status" -eq 0 ] || { echo "$output"; false; }

	run python3 \
		"$BATS_TEST_DIRNAME/test_helper/guidance_contracts.py" \
		issue-stage-order \
		"$BATS_TEST_DIRNAME/../skills/kramme:siw:issue-to-pr/SKILL.md"
	[ "$status" -eq 0 ] || { echo "$output"; false; }
}

@test "generated plan-to-PR enforces dependency drift scope and artifact isolation" {
	run bash -c '
    set -e
    cd "'"$BATS_TEST_DIRNAME"'/.."
	    skill="skills/kramme:code:plan-to-pr/SKILL.md"
	    attachment="skills/kramme:code:plan-to-pr/references/attachment-input.md"
	    breakdown="skills/kramme:code:breakdown-findings/SKILL.md"
		    plan_template="skills/kramme:code:breakdown-findings/assets/plan-template.md"
		    generated_index_template="skills/kramme:code:breakdown-findings/assets/index-template.md"
		    reconcile="skills/kramme:code:breakdown-findings/references/reconcile-workflow.md"
	    plan_requirements="skills/kramme:code:breakdown-findings/references/plan-content-requirements.md"
	    generation_checks="skills/kramme:code:breakdown-findings/references/generation-checks.md"
    completion="skills/kramme:pr:complete-work/SKILL.md"
    convergence="skills/kramme:pr:review-convergence/SKILL.md"
    handoff="skills/kramme:pr:review-convergence/references/standalone-scope-handoff.md"
    review="skills/kramme:pr:review-convergence/references/review-convergence.md"
    shipping="skills/kramme:pr:complete-work/references/shipping-contract.md"
    fix_ci="skills/kramme:pr:fix-ci/SKILL.md"
    fix_ci_scope="skills/kramme:pr:fix-ci/references/scoped-plan.md"
    index_asset="skills/kramme:code:plan-to-pr/assets/standalone-index-template.md"
    rejections_asset="skills/kramme:code:plan-to-pr/assets/standalone-rejections-template.md"

    test -f "$skill"
	    test -f "$attachment"
	    test -f "$breakdown"
	    test -f "$plan_template"
		    test -f "$generated_index_template"
		    test -f "$reconcile"
	    test -f "$plan_requirements"
	    test -f "$generation_checks"
    test -f "$completion"
    test -f "$convergence"
    test -f "$handoff"
    test -f "$index_asset"
    test -f "$rejections_asset"
    test -f "$fix_ci"
    test -f "$fix_ci_scope"
	    grep -qF "argument-hint: \"<attached plan | PR_PLAN_W##L_*.md> [--strict] [--ship]\"" "$skill"
	    grep -qF "A copied plan is also a self-standing execution capsule" "$breakdown"
	    grep -qF "the index organizes the set but is never an implementation prerequisite" "$breakdown"
	    grep -qF "### Prerequisite Readiness Evidence" "$plan_template"
	    grep -qF "Make this plan executable without sibling plans or PR_PLAN_INDEX.md" "$plan_template"
	    grep -qF "never an existing directory or a directory-containment grant" "$plan_template"
	    grep -qF "exact evidence locations, and a binary readiness decision" "$plan_requirements"
	    grep -qF "Every In Scope entry must identify one repository-relative file" "$plan_requirements"
	    grep -qF "Every plan remains executable when copied by itself into a fresh workspace" "$generation_checks"
	    grep -qF "no entry resolves to an existing directory" "$generation_checks"
	    grep -qF "**Scope contract:** exact files" "$plan_template"
		    grep -qF "**Scope contract:** exact files" "$generated_index_template"
		    grep -qF "Valid active statuses: \`TODO\`, \`READY\`, \`IN_PROGRESS\`, \`BLOCKED\`, \`DRIFTED\`, \`STALE\`." "$generated_index_template"
		    grep -qF "Reserve \`IN_PROGRESS\` for an executor that has claimed a plan" "$breakdown"
		    grep -qF "matching index row starts at \`TODO\`" "$generation_checks"
	    grep -qF "Preserve exactly one opening metadata field" "$plan_requirements"
	    grep -qF "Every generated plan and \`PR_PLAN_INDEX.md\` contains exactly one opening metadata field" "$generation_checks"
    grep -qF "PR_PLAN_INDEX.md" "$skill"
    grep -qF "PR_PLAN_REJECTIONS.md" "$skill"
    grep -qF "**Attachment input:** a file anywhere below the repository'\''s \`.context/attachments/\` directory." "$skill"
    grep -qF "A file below \`.context/attachments/\` is always one standalone attachment" "$skill"
    grep -qF "The validated path is the sole intake classifier" "$skill"
    grep -qF "For \`attachment\`, read only the selected attachment" "$skill"
    grep -qF "A valid detached \`W##L\` attachment is not an incomplete generated set" "$skill"
    grep -qF "never replace that diagnosis with a request for the complete \`PR_PLAN_*.md\` set" "$skill"
    grep -qF "derive \`{selected-basename}\` from the plan'\''s canonical \`**File:**\` declaration" "$skill"
    grep -qF "Store \`{plan-input-mode}\` as \`root\`, \`attachment\`, or \`archived\`." "$skill"
    grep -qF "For archived input, allow \`PR_PLAN_[A-Z][0-9][0-9][A-Z]_[A-Z0-9_]+.md\`" "$skill"
    grep -qF "never downgrade it to an ordinary generated set" "$skill"
    grep -qF "archive provenance, not the label alone, distinguishes a complete generated set from a normalized singleton attachment" "$skill"
    grep -qF "that reference also sets \`DETACHED_GENERATED_PLAN\` from the validated attachment contract" "$skill"
    grep -qF "require the selected basename to match the generated \`PR_PLAN_W[0-9][0-9][A-Z]_[A-Z0-9_]+.md\` contract" "$skill"
    grep -qF "set \`STANDALONE_ATTACHMENT=true\`" "$skill"
    grep -qF "require the full normalized-archive contract to pass" "$skill"
    grep -qF ".context/code-plan-to-pr/{plan-set-id}/plans/{selected-basename}" "$skill"
    grep -qF "preserve the source attachment, copy its exact bytes" "$skill"
    grep -qF "immutable \`ATTACHMENT_SOURCE.md\` snapshot" "$skill"
    grep -qF "require file-level scope" "$skill"
    grep -qF "Reject duplicate normalized paths." "$skill"
    grep -qF "Store the normalized values in \`SCOPE_PATHS\`" "$skill"
    grep -qF "never render a plan value into shell command text" "$skill"
    grep -qF "Git administrative directory and reject" "$skill"
    grep -qF "git check-ignore --index -z --stdin" "$skill"
    ! grep -qF "git check-ignore --index -q -z --stdin" "$skill"
    grep -qF "first matching path as the exact blocker" "$skill"
    grep -qF "Never add \`--no-index\`" "$skill"
    grep -qF "Re-run these eligibility checks in one batch immediately before staging" "$skill"
    grep -qF "Validate a Standalone Terminal Retry" "$skill"
    grep -qF "exact equality with one normalized scope path when \`PLAN_SCOPE_MODE=exact-files\`" "$skill"
    grep -qF "When each artifact contains exactly one opening metadata field \`**Scope contract:** exact files\`, set \`PLAN_SCOPE_MODE=exact-files\`." "$skill"
    grep -qF "When every artifact omits the field, set \`PLAN_SCOPE_MODE=containment\` for legacy compatibility." "$skill"
    grep -qF "Reject duplicate fields, unknown values, or a marker present in only part of the set" "$skill"
    grep -qF "git add -- \"\${GIT_PATHS[@]}\"" "$skill"
    grep -qF "Load this reference for either direct intake" "$attachment"
    grep -qF "the attachment is deliberately the complete input" "$attachment"
    grep -qF "Do not search for or request the source \`PR_PLAN_INDEX.md\`" "$attachment"
    grep -qF "they never change a direct attachment into root input" "$attachment"
    grep -qF "Every archived retry uses \`Validate a Normalized Archive\`; a \`DONE\` retry must also use \`Validate a Standalone Terminal Retry\`" "$attachment"
    grep -qF "strictly below" "$attachment"
    grep -qF "canonical attachment root and input to remain strictly below the canonical repository root" "$attachment"
    grep -qF "require it to match \`^[A-Za-z0-9._/ -]+$\`" "$attachment"
    grep -qF "never render the raw argument into a shell command" "$attachment"
    grep -qF "A \`W##L\` label identifies a detached generated plan" "$attachment"
    grep -qF "backticked basename matches \`^PR_PLAN_[A-Z][0-9][0-9][A-Z]_[A-Z0-9_]+\\.md$\`" "$attachment"
    grep -qF "backticked value matches \`^[A-Z][0-9][0-9][A-Z]$\`" "$attachment"
    grep -qF "also accept \`BLOCKED\` only when \`DETACHED_GENERATED_PLAN=true\`" "$attachment"
	    grep -qF "prefer exactly one matching \`#### W##L\` entry under \`### Prerequisite Readiness Evidence\`" "$attachment"
	    grep -qF "For a legacy generated plan that predates this heading" "$attachment"
	    grep -qF "A bare statement that \`W##L\` must land is insufficient." "$attachment"
	    grep -qF "Reject evidence that depends on \`PR_PLAN_INDEX.md\`, a sibling plan" "$attachment"
	    grep -qF "accept only a legacy normalized independent archive" "$attachment"
	    grep -qF "perform a one-time deterministic migration" "$attachment"
    grep -qF "standalone-attachment" "$attachment"
    grep -qF "stable across attachment filename rewrites" "$attachment"
    grep -qF "require both the new \`{plan-source-object-id}\` and \`{plan-set-id}\` to differ" "$attachment"
    grep -qF "Require \`.context\` to be a real non-symlink directory whose canonical path is strictly below the canonical repository root." "$attachment"
    grep -qF "final archive absent until every staged artifact" "$attachment"
    grep -qF "Revalidate the non-symlink \`.context\` and \`.context/code-plan-to-pr/\` parent chain" "$attachment"
    grep -qF "both to \`{selected-basename}\` and to \`ATTACHMENT_SOURCE.md\`" "$attachment"
    grep -qF "**Source snapshot:** \`ATTACHMENT_SOURCE.md\`" "$index_asset"
    grep -qF "**Attachment contract:** {attachment-contract}" "$index_asset"
    grep -qF "{sequencing-summary}" "$index_asset"
    grep -qF "## Validate a Normalized Archive" "$attachment"
    grep -qF "require \`{selected-basename}\` to match \`PR_PLAN_[A-Z][0-9][0-9][A-Z]_[A-Z0-9_]+.md\`" "$attachment"
    grep -qF "exactly one \`PR_PLAN_[A-Z][0-9][0-9][A-Z]_*.md\` implementation plan" "$attachment"
    grep -qF "require \`ps-{recomputed-object-id}\` to equal \`{plan-set-id}\`" "$attachment"
    grep -qF "With no \`## Workflow State\` or \`## Execution Result\`" "$attachment"
	    grep -qF "With status \`TODO\`, \`READY\`, or \`IN_PROGRESS\`, or with \`BLOCKED\` only for a detached generated plan" "$attachment"
    grep -qF "With status \`DONE\`, require exactly one \`## Execution Result\`" "$attachment"
    grep -qF "terminal \`## Workflow State\` at \`COMPLETE\` or \`PUBLISHED_BLOCKED\`" "$attachment"
    grep -qF "require the remaining bytes to match exactly" "$attachment"
    grep -qF "assets/standalone-index-template.md" "$attachment"
    grep -qF "assets/standalone-rejections-template.md" "$attachment"
    grep -qF "## Validate a Standalone Terminal Retry" "$attachment"
    grep -qF "Require the completion commit to equal the checkpoint head" "$attachment"
    grep -qF "store it as \`{proven-base-commit}\`, and require the recorded base commit to equal it" "$attachment"
    grep -qF "git merge-base --is-ancestor \"{checkpoint-head}\" \"origin/{base-branch}\"" "$attachment"
    grep -qF "complete ordered Pull Request commit inventory" "$attachment"
    grep -qF "require the first commit'\''s sole parent to equal the recorded base commit" "$attachment"
    grep -qF "git rev-list --first-parent --reverse \"{recorded-base-commit}\"..\"{checkpoint-head}\"" "$attachment"
    grep -qF "\`{proven-base-commit}..{checkpoint-head}\`" "$attachment"
    grep -qF "Prove the terminal head from at least one authoritative ref" "$attachment"
    grep -qF "exactly one \`Recovery\` payload" "$attachment"
    grep -qF "With only a remote branch, require a manual Pull Request creation payload" "$attachment"
    grep -qF "When exactly one same-repository open Pull Request now exists" "$attachment"
    grep -qF "atomically update only the archived publication state and execution-result Pull Request number" "$attachment"
    grep -qF "No companion rejection data was supplied with this attached plan." "$rejections_asset"
    grep -qF "**Input mode:** standalone attachment" "$index_asset"
    grep -qF "for a detached generated attachment, defer readiness to the embedded-evidence proof in Step 4" "$skill"
    grep -qF "do not request or search for the source index or sibling plans" "$skill"
    grep -qF "do not ask for \`PR_PLAN_INDEX.md\`" "$skill"
		    grep -qF "Keep the detached plan'\''s archived plan/index status unchanged while proving prerequisites in this step" "$skill"
		    grep -qF "do not persist \`READY\`" "$skill"
	    grep -qF "one bounded exception only to recover a detached generated attachment interrupted after its implementation commit" "$skill"
	    grep -qF "**Archived input:** \`.context/code-plan-to-pr/{plan-set-id}/plans/\`" "$skill"
    grep -qF "whose canonical paths remain strictly below the canonical repository root" "$skill"
    grep -qF "Store that canonical repository-relative input immediately as \`{validated-scope-plan}\`" "$skill"
	    grep -qF "Build a deterministic binary manifest from every root \`PR_PLAN_*.md\` artifact" "$skill"
	    grep -qF "git hash-object --no-filters -- \"{basename}\"" "$skill"
	    grep -qF "Hash the manifest with \`git hash-object --stdin\`" "$skill"
	    grep -qF "any index, plan-body, rejection-record, filename, or inventory change creates a different set identity" "$skill"
	    grep -qF "Use the full \`{plan-set-id}\` for storage" "$skill"
    grep -qF "kramme:code:breakdown-findings --reconcile" "$skill"
    grep -qF "Reject plans containing an \`## Implementation Setup\` section." "$skill"
    grep -qF "Do not execute the plan'\''s command blocks." "$skill"
    grep -qF "build a Git pathspec as \`:(literal){path}\`" "$skill"
    grep -qF "git diff --stat \"{planned-at}\" -- \"\${GIT_PATHS[@]}\"" "$skill"
    grep -qF "git status --short -- \"\${GIT_PATHS[@]}\"" "$skill"
    grep -qF "Keep the established archive in place." "$skill"
    grep -qF "never retain a root or attachment source path as the active plan" "$skill"
    grep -qF "preserves either the complete generated plan set or the normalized singleton attachment" "$skill"
    grep -qF "every dirty path is a root-level \`PR_PLAN_*.md\` file" "$skill"
    grep -qF "git ls-files --error-unmatch -- \":(literal){path}\"" "$skill"
	    grep -qF "gh pr view \"{url}\" --json state,mergedAt,baseRefName,mergeCommit" "$skill"
	    grep -qF "git check-ref-format --branch \"{final-branch}\"" "$skill"
	    grep -qF "gh pr list --head \"{final-branch}\" --state all" "$skill"
	    grep -qF "require an exact same-repository GitHub Pull Request URL with a numeric identifier" "$skill"
    grep -qF "Reject symbolic refs, abbreviated OIDs, and leading \`-\`." "$skill"
    grep -qF "git merge-base --is-ancestor \"{landing-commit}\" \"origin/{base-branch}\"" "$skill"
    grep -qF "require its tip to equal the fetched \`origin/{base-branch}\` tip exactly" "$skill"
	    grep -qF "never adopt, reset, delete, or rewrite an uncheckpointed local branch with commits" "$skill"
    grep -qF "git diff --name-only \"{proven-base-commit}\"..\"{checkpoint-head}\"" "$skill"
    grep -qF "git merge-base \"{checkpoint-head}\" \"origin/{base-branch}\"" "$skill"
    grep -qF "set \`{branch-base-commit}\` from \`{proven-base-commit}\`" "$skill"
	    grep -qF "When \`COMPLETION_RESUME=true\`, do not invoke \`kramme:code:work-from-plan\` again" "$skill"
	    grep -qF "Stage: IMPLEMENTED" "$skill"
	    grep -qF "Stage: QUALITY_BLOCKED" "$skill"
	    grep -qF "Stage: PUBLISHED_BLOCKED" "$skill"
	    grep -qF "structured disposition to be \`prepublication_blocked\` or \`published_blocked\`" "$skill"
	    grep -qF "The mere appearance of a concurrent remote branch is never evidence" "$skill"
	    grep -qF "out-of-scope post-publication path" "$skill"
    grep -qF "kramme:code:work-from-plan" "$skill"
    grep -qF "route \`direct\`" "$skill"
    grep -qF -- "--archive-key code-plan-to-pr" "$skill"
    grep -qF -- "--scope-plan {active-plan}" "$skill"
    grep -qF "Require the delegated work branch and local head/tree to equal the observed branch" "$skill"
    grep -qF "stop without advancing plan state on the first mismatch" "$skill"
    grep -qF "Set the selected plan header and matching index row to \`DONE\`." "$skill"
    grep -qF "full completion commit OID" "$skill"
    grep -qF "Do not record a \`Landed commit\` merely because implementation or Pull Request creation completed." "$skill"
    grep -qF "Later plan input: pass the selected archived \`PR_PLAN_<label>_*.md\` path" "$skill"
    grep -qF "never invoke broad workflow-artifact cleanup" "$skill"
    grep -qF "PR_PLAN_[A-Z][0-9][0-9][A-Z]_[A-Z0-9_]+.md" "$convergence"
    grep -qF "Archive provenance distinguishes complete generated sets from singleton attachments, including detached \`W##L\` plans." "$convergence"
    grep -qF "references/standalone-scope-handoff.md" "$convergence"
    grep -qF "Require \`.context\`, \`.context/code-plan-to-pr\`, and every later parent to be real non-symlink directories" "$convergence"
    grep -qF "PLAN_SCOPE_MODE=exact-files" "$convergence"
    grep -qF "PLAN_SCOPE_MODE=containment" "$convergence"
    grep -qF "RECHECK_STANDALONE_SCOPE" "$convergence"
    grep -qF "store it as \`{proven-scope-base}\`, and require the recorded base commit to equal it" "$convergence"
    grep -qF "continue to item 5 without setting \`DONE\` or \`PUBLISHED_BLOCKED\`" "$skill"
    grep -qF "the exact delegated \`Recovery\` payload" "$skill"
    grep -qF "Report only that recorded recovery (the exact synced scoped recovery payload when a Pull Request exists" "$skill"
    grep -qF "## Validate Standalone Provenance" "$handoff"
	    grep -qF "set \`STANDALONE_ARCHIVE=false\`" "$handoff"
	    grep -qF "when every artifact contains the field" "$handoff"
	    grep -qF "when every artifact omits it for legacy compatibility" "$handoff"
	    grep -qF "A \`W##L\` singleton must declare \`**Attachment contract:** detached generated plan\`" "$handoff"
	    grep -qF "a \`W##L\` singleton to declare \`detached generated plan\`" "$fix_ci_scope"
	    grep -qF "set \`DETACHED_GENERATED_PLAN=true\`" "$handoff"
		    grep -qF "accept \`IN_PROGRESS\`; for a legacy checkpoint" "$handoff"
	    grep -qF "set \`DETACHED_GENERATED_PLAN=true\`" "$fix_ci_scope"
		    grep -qF "status \`IN_PROGRESS\`; for a legacy checkpoint" "$fix_ci_scope"
	    grep -qF "legacy normalized independent archive" "$handoff"
	    grep -qF "one-time deterministic migration" "$handoff"
	    grep -qF "legacy normalized independent archive" "$fix_ci_scope"
	    grep -qF "one-time deterministic migration" "$fix_ci_scope"
    grep -qF "the exact \`**Input mode:** standalone attachment\` marker in the index or rejection record" "$skill"
    grep -qF "the exact \`**Input mode:** standalone attachment\` marker in the index or rejection record" "$handoff"
    grep -qF "Require \`{selected-basename}\` to match \`PR_PLAN_[A-Z][0-9][0-9][A-Z]_[A-Z0-9_]+.md\`" "$handoff"
    grep -qF "## Preserve Exact-File Scope" "$handoff"
    grep -qF "git check-ignore --index -z --stdin" "$handoff"
    ! grep -qF "git check-ignore --index -q -z --stdin" "$handoff"
    grep -qF "first matching path as the exact blocker" "$handoff"
    grep -qF "Run \`RECHECK_STANDALONE_SCOPE\` when \`PLAN_SCOPE_ACTIVE=true\` and \`PLAN_SCOPE_MODE=exact-files\`, then stage only" "$review"
    grep -qF "Before every fix commit or push" "$shipping"
    grep -qF "under its scoped-plan mutation contract" "$shipping"
    grep -qF "Synced atomic scoped archive update contract (keep aligned across plan recovery)" "$shipping"
    grep -qF "write the complete updated selected plan to a non-symlink temporary sibling" "$shipping"
    grep -qF "atomically rename that sibling over the selected plan" "$shipping"
    grep -qF "leave the previous plan intact and treat the already-published mutation as interrupted" "$shipping"
    grep -qF "Use that atomic replacement to update only the archived workflow-state checkpoint head/tree" "$shipping"
    grep -qF "A later session resumes with that exact invocation" "$shipping"
    grep -qF "Recovery: {fix-ci-invocation}" "$shipping"
    ! grep -qF "Recovery: \${fix-ci-invocation}" "$shipping"
    grep -qF "argument-hint: \"[--fixup] [--auto] [--no-consolidate] [--scope-plan <archived-plan>]\"" "$fix_ci"
    grep -qF "SCOPED_PLAN_LIFECYCLE=recovery" "$fix_ci_scope"
	    grep -qF "set \`STANDALONE_ARCHIVE=false\`" "$fix_ci_scope"
	    grep -qF "when every artifact contains the field" "$fix_ci_scope"
	    grep -qF "when every artifact omits it for legacy compatibility" "$fix_ci_scope"
    grep -qF "derive \`{validated-plan-branch}\` as \`plan/{plan-set-short}-{execution-label-lowercase}-{plan-slug}\`" "$fix_ci_scope"
    grep -qF "Before any Git or GitHub CLI use" "$fix_ci_scope"
    grep -qF "reject a leading \`-\`" "$fix_ci_scope"
    grep -qF "pass \`git check-ref-format --branch\`" "$fix_ci_scope"
    grep -qF "require the current and recorded branches to equal \`{validated-plan-branch}\`" "$fix_ci_scope"
    grep -qF "Before every push, revalidate all committed paths" "$fix_ci_scope"
    grep -qF "Synced atomic scoped archive update contract (keep aligned across plan recovery)" "$fix_ci_scope"
    grep -qF "write the complete updated selected plan to a non-symlink temporary sibling" "$fix_ci_scope"
    grep -qF "atomically rename that sibling over the selected plan" "$fix_ci_scope"
    grep -qF "leave the previous plan intact and treat the already-published mutation as interrupted" "$fix_ci_scope"
    grep -qF "immediately after every proven push use the atomic archive update contract above to replace only the archived workflow-state checkpoint head/tree" "$fix_ci_scope"
    grep -qF "immediately after every proven push use the same atomic archive update contract to replace the archived checkpoint head/tree" "$fix_ci_scope"
    grep -qF "Ancestor-only scoped push" "$fix_ci_scope"
    grep -qF "the first commit'\''s sole parent is \`{checkpoint-head}\`" "$fix_ci_scope"
    grep -qF "Reject merge commits, missing or reordered commits" "$fix_ci_scope"
    grep -qF "Tree-identical narrative rewrite" "$fix_ci_scope"
    grep -qF "every path touched by each commit against its sole parent" "$fix_ci_scope"
    grep -qF "atomically refresh only the workflow-state checkpoint head/tree" "$fix_ci_scope"
    grep -qF "repeat every archive identity, base, same-repository Pull Request identity, head agreement, tree, exact-file eligibility, and committed-path proof" "$fix_ci_scope"
    grep -qF "When \`PLAN_SCOPE_ACTIVE=true\`, fail closed without invoking \`/kramme:pr:rebase\` or changing history" "$fix_ci"
    grep -qF "require a refreshed or explicitly re-authorized scoped plan before continuing" "$fix_ci"
    grep -qF "capture the full current \`HEAD\` as \`{validated-push-head}\`" "$fix_ci"
    grep -qF "git push origin \"{validated-push-head}:refs/heads/{validated-plan-branch}\"" "$fix_ci"
    grep -qF "require the local branch tip to remain \`{validated-push-head}\`" "$fix_ci"
    grep -qF "stop before editing, staging, committing, or pushing that fix" "$shipping"
    grep -qF "Before returning a blocked handoff" "$shipping"
    grep -qF "Stop before history rewriting or publication on the first mismatch or newly ineligible exact-file path." "$shipping"
    grep -qF "If any path falls outside \`VALIDATED_SCOPE_PATHS\` or an exact-file path is newly ineligible" "$shipping"

    validate_line=$(grep -nF "## Step 2: Validate the Plan Set" "$skill" | cut -d: -f1)
    archive_line=$(grep -nF "## Step 3: Archive Planning Artifacts" "$skill" | cut -d: -f1)
    branch_line=$(grep -nF "## Step 4: Establish the Plan Branch" "$skill" | cut -d: -f1)
    implement_line=$(grep -nF "## Step 5: Implement the Plan" "$skill" | cut -d: -f1)
    complete_line=$(grep -nF "## Step 6: Complete the Pull Request Workflow" "$skill" | cut -d: -f1)
    [ "$validate_line" -lt "$archive_line" ]
    [ "$archive_line" -lt "$branch_line" ]
    [ "$branch_line" -lt "$implement_line" ]
    [ "$implement_line" -lt "$complete_line" ]
  '

	[ "$status" -eq 0 ] || { echo "$output"; false; }

	run python3 \
		"$BATS_TEST_DIRNAME/test_helper/guidance_contracts.py" \
		detached-plan-compatibility \
		"$BATS_TEST_DIRNAME/.."
	[ "$status" -eq 0 ] || { echo "$output"; false; }
}

@test "shared completion workflow preserves ordered bounded review and shipping proof" {
	run bash -c '
    set -e
    cd "'"$BATS_TEST_DIRNAME"'/.."
    skill="skills/kramme:pr:complete-work/SKILL.md"
    convergence="skills/kramme:pr:review-convergence/SKILL.md"
    review="skills/kramme:pr:review-convergence/references/review-convergence.md"
    shipping="skills/kramme:pr:complete-work/references/shipping-contract.md"

    test -f "$skill"
    test -f "$convergence"
    test -f "$review"
    test -f "$shipping"
    grep -qF "user-invocable: false" "$skill"
    grep -qF "Accept only \`siw-issue-to-pr\` or \`code-plan-to-pr\`" "$skill"
    grep -qF "require it exactly once for \`code-plan-to-pr\`" "$convergence"
    grep -qF "Store the exact normalized list as \`VALIDATED_SCOPE_PATHS\`" "$convergence"
    grep -qF "every proposed and dirty path" "$review"
    grep -qF "Stop before history rewriting or publication on the first mismatch" "$shipping"
    grep -qF "gh pr list --head \"{work-branch}\" --state all" "$skill"
    grep -qF "git ls-remote --heads origin \"refs/heads/{work-branch}\"" "$skill"
    grep -qF "kramme:pr:review-convergence" "$skill"
    grep -qF "JSON-decode its \`Requirements JSON\` field" "$skill"
    grep -qF "equal \`{work-requirements}\` byte-for-byte" "$skill"
    grep -qF "**Internal \`code-plan-to-pr\`:** treat the validated plan—not \`{supplied-requirements}\`—as authoritative" "$convergence"
    grep -qF "validation-only mode permits later caller-authorized CI/review commits" "$convergence"
    grep -qF "kramme:pr:code-review --parallel --inline" "$review"
    grep -qF "kramme:pr:convention-review --inline" "$review"
    grep -qF "kramme:code:refactor-opportunities" "$review"
	    grep -qF "kramme:verify:run" "$convergence"
	    grep -qF "Completion disposition: success | prepublication_blocked | published_blocked" "$skill"
	    grep -qF "Pre-publication quality and verification: passed" "$skill"
	    grep -qF "Publication state: absent | remote branch only | open Pull Request" "$skill"
	    grep -qF "Work branch: {work-branch}" "$skill"

    grep -qF "MAX_AUTOMATIC_REMEDIATION_CYCLES=5" "$review"
    grep -qF "one complete ordered pass" "$review"
    grep -qF "Do not consume a cycle or restart applicability." "$review"
    grep -qF ".context/{archive-key}/reviews/" "$review"

    grep -qF "kramme:pr:create --auto --require-generated-description --authorize-history-rewrite" "$shipping"
    grep -qF "kramme:pr:fix-ci --no-consolidate" "$shipping"
	    grep -qF "Do not combine it with \`--auto\`." "$shipping"
	    grep -qF "Completion disposition: published_blocked" "$shipping"
	    grep -qF "Work branch: {work-branch}" "$shipping"
	    grep -qF "Blocker: {exact delegated blocker}" "$shipping"
	    grep -qF "Publication state: remote branch only" "$shipping"
	    grep -qF "callers must persist their implementation-complete source state" "$shipping"
    grep -qF "git rev-parse '\''HEAD^{tree}'\''" "$shipping"
    grep -qF "headRefOid" "$shipping"
    grep -qF "gh pr checks --json name,state,bucket,link,workflow" "$shipping"
    grep -qF "no checks reported" "$shipping"
    grep -qF "reviewThreads(first: 100, after: \$endCursor)" "$shipping"
    grep -qF "kramme:verify:run" "$shipping"
    grep -qF "exact frozen sentinel-last \`--requirements {work-requirements}\` block" "$shipping"
    grep -qF "JSON-decode the returned \`Requirements JSON\` field" "$shipping"
  '

	[ "$status" -eq 0 ] || { echo "$output"; false; }

	run python3 \
		"$BATS_TEST_DIRNAME/test_helper/guidance_contracts.py" \
		review-gate-order \
		"$BATS_TEST_DIRNAME/../skills/kramme:pr:review-convergence/references/review-convergence.md"
	[ "$status" -eq 0 ] || { echo "$output"; false; }
}

@test "single SIW issue auto mode remains evidence gated" {
	run bash -c '
    set -e
    cd "'"$BATS_TEST_DIRNAME"'/.."
    skill="skills/kramme:siw:issue-implement/SKILL.md"
    closeout="skills/kramme:siw:issue-implement/references/issue-closeout.md"

    grep -qF "argument-hint: \"<issue-id> [--auto] | --team [issue-ids | '\''phase N'\''] [--auto]\"" "$skill"
    grep -qF "set \`AUTO_MODE=true\`" "$skill"
    grep -qF "auto mode never assumes ownership of pre-existing work" "$skill"
    grep -qF "Gate Existing Status Before Implementation" "$skill"
    grep -qF "standard auto mode must not reset it to \`IN PROGRESS\`" "$skill"
    grep -qF "The closeout idempotency check remains as a final race-safe guard" "$skill"
    grep -qF "AUTO: proceeding with autonomous implementation" "$skill"
    grep -qF "skip the approach question and choose **Autonomous Implementation**" "$skill"
    grep -qF "never bypasses dirty-worktree handling, HITL confirmation" "$skill"
    grep -qF "If \`AUTO_MODE=true\`, do not ask the confidence question." "$closeout"
    grep -qF "\`DONE\` only when every acceptance criterion is satisfied" "$closeout"
    grep -qF "\`IN REVIEW\` when implementation and automated verification are complete" "$closeout"

    status_gate=$(grep -nF "### 1.3 Gate Existing Status Before Implementation" "$skill" | cut -d: -f1)
    git_state=$(grep -nF "## Step 2: Verify Git State" "$skill" | cut -d: -f1)
    auto_approach=$(grep -nF "If \`AUTO_MODE=true\`, skip the approach question" "$skill" | cut -d: -f1)
    [ "$status_gate" -lt "$git_state" ]
    [ "$git_state" -lt "$auto_approach" ]
  '

	[ "$status" -eq 0 ]
}

@test "new review archives are registered without deleting plan handoff state" {
	run bash -c '
    set -e
    cd "'"$BATS_TEST_DIRNAME"'/.."
    registry="skills/kramme:workflow-artifacts:cleanup/references/disposable-artifacts.yaml"

    grep -qF "\"path\": \".context/siw-issue-to-pr/reviews/REVIEW_OVERVIEW.md\"" "$registry"
    grep -qF "\"path\": \".context/siw-issue-to-pr/reviews/CONVENTION_REVIEW_OVERVIEW.md\"" "$registry"
    grep -qF "\"path\": \".context/siw-issue-to-pr/reviews/REFACTOR_OPPORTUNITIES_OVERVIEW.md\"" "$registry"
    grep -qF "\"path\": \".context/code-plan-to-pr/reviews/REVIEW_OVERVIEW.md\"" "$registry"
    grep -qF "\"path\": \".context/code-plan-to-pr/reviews/CONVENTION_REVIEW_OVERVIEW.md\"" "$registry"
    grep -qF "\"path\": \".context/code-plan-to-pr/reviews/REFACTOR_OPPORTUNITIES_OVERVIEW.md\"" "$registry"
    grep -qF "\"path\": \".context/pr-review-convergence/reviews/OVERENGINEERING_REVIEW_OVERVIEW.md\"" "$registry"
    ! grep -qF "\"path\": \".context/code-plan-to-pr/\"" "$registry"
    ! grep -qF "\"path\": \".context/siw-issue-to-pr/\"" "$registry"
  '

	[ "$status" -eq 0 ]
}
